export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';

export const FETCH_RECIPES_START = 'FETCH_RECIPES_START';
export const FETCH_RECIPES_SUCCESS = 'FETCH_RECIPES_SUCCESS';
export const FETCH_RECIPES_FAIL = 'FETCH_RECIPES_FAIL';
export const ADD_RECIPE_START = 'ADD_RECIPE_START';
export const ADD_RECIPE_SUCCESS = 'ADD_RECIPE_SUCCESS';
export const ADD_RECIPE_FAIL = 'ADD_RECIPE_FAIL';
export const EDIT_RECIPE_START = 'EDIT_RECIPE_START';
export const EDIT_RECIPE_SUCCESS = 'EDIT_RECIPE_SUCCESS';
export const EDIT_RECIPE_FAIL = 'EDIT_RECIPE_FAIL';
export const DELETE_RECIPE_START = 'DELETE_RECIPE_START';
export const DELETE_RECIPE_SUCCESS = 'DELETE_RECIPE_SUCCESS';
export const DELETE_RECIPE_FAIL = 'DELETE_RECIPE_FAIL';

export const FETCH_INGREDIENTS_START = 'FETCH_INGREDIENTS_START';
export const FETCH_INGREDIENTS_SUCCESS = 'FETCH_INGREDIENTS_SUCCESS';
export const FETCH_INGREDIENTS_FAIL = 'FETCH_INGREDIENTS_FAIL';
export const ADD_INGREDIENT_START = 'ADD_INGREDIENT_START';
export const ADD_INGREDIENT_SUCCESS = 'ADD_INGREDIENT_SUCCESS';
export const ADD_INGREDIENT_FAIL = 'ADD_INGREDIENT_FAIL';
export const EDIT_INGREDIENT_START = 'EDIT_INGREDIENT_START';
export const EDIT_INGREDIENT_SUCCESS = 'EDIT_INGREDIENT_SUCCESS';
export const EDIT_INGREDIENT_FAIL = 'EDIT_INGREDIENT_FAIL';
export const DELETE_INGREDIENT_START = 'DELETE_INGREDIENT_START';
export const DELETE_INGREDIENT_SUCCESS = 'DELETE_INGREDIENT_SUCCESS';
export const DELETE_INGREDIENT_FAIL = 'DELETE_INGREDIENT_FAIL';

export const FETCH_INGREDIENT_CATEGORIES_START = 'FETCH_INGREDIENT_CATEGORIES_START';
export const FETCH_INGREDIENT_CATEGORIES_SUCCESS = 'FETCH_INGREDIENT_CATEGORIES_SUCCESS';
export const FETCH_INGREDIENT_CATEGORIES_FAIL = 'FETCH_INGREDIENT_CATEGORIES_FAIL';
export const ADD_INGREDIENT_CATEGORIES_START = 'ADD_INGREDIENT_CATEGORIES_START';
export const ADD_INGREDIENT_CATEGORIES_SUCCESS = 'ADD_INGREDIENT_CATEGORIES_SUCCESS';
export const ADD_INGREDIENT_CATEGORIES_FAIL = 'ADD_INGREDIENT_CATEGORIES_FAIL';
export const EDIT_INGREDIENT_CATEGORIES_START = 'EDIT_INGREDIENT_CATEGORIES_START';
export const EDIT_INGREDIENT_CATEGORIES_SUCCESS = 'EDIT_INGREDIENT_CATEGORIES_SUCCESS';
export const EDIT_INGREDIENT_CATEGORIES_FAIL = 'EDIT_INGREDIENT_CATEGORIES_FAIL';
export const DELETE_INGREDIENT_CATEGORIES_START = 'DELETE_INGREDIENT_CATEGORIES_START';
export const DELETE_INGREDIENT_CATEGORIES_SUCCESS = 'DELETE_INGREDIENT_CATEGORIES_SUCCESS';
export const DELETE_INGREDIENT_CATEGORIES_FAIL = 'DELETE_INGREDIENT_CATEGORIES_FAIL';

export const FETCH_MEASUREMENT_UNITS_START = 'FETCH_MEASUREMENT_UNITS_START';
export const FETCH_MEASUREMENT_UNITS_SUCCESS = 'FETCH_MEASUREMENT_UNITS_SUCCESS';
export const FETCH_MEASUREMENT_UNITS_FAIL = 'FETCH_MEASUREMENT_UNITS_FAIL';
export const ADD_MEASUREMENT_UNITS_START = 'ADD_MEASUREMENT_UNITS_START';
export const ADD_MEASUREMENT_UNITS_SUCCESS = 'ADD_MEASUREMENT_UNITS_SUCCESS';
export const ADD_MEASUREMENT_UNITS_FAIL = 'ADD_MEASUREMENT_UNITS_FAIL';
export const EDIT_MEASUREMENT_UNITS_START = 'EDIT_MEASUREMENT_UNITS_START';
export const EDIT_MEASUREMENT_UNITS_SUCCESS = 'EDIT_MEASUREMENT_UNITS_SUCCESS';
export const EDIT_MEASUREMENT_UNITS_FAIL = 'EDIT_MEASUREMENT_UNITS_FAIL';
export const DELETE_MEASUREMENT_UNITS_START = 'DELETE_MEASUREMENT_UNITS_START';
export const DELETE_MEASUREMENT_UNITS_SUCCESS = 'DELETE_MEASUREMENT_UNITS_SUCCESS';
export const DELETE_MEASUREMENT_UNITS_FAIL = 'DELETE_MEASUREMENT_UNITS_FAIL';

export const FETCH_RECIPE_CATEGORIES_START = 'FETCH_RECIPE_CATEGORIES_START';
export const FETCH_RECIPE_CATEGORIES_SUCCESS = 'FETCH_RECIPE_CATEGORIES_SUCCESS';
export const FETCH_RECIPE_CATEGORIES_FAIL = 'FETCH_RECIPE_CATEGORIES_FAIL';
export const ADD_RECIPE_CATEGORIES_START = 'ADD_RECIPE_CATEGORIES_START';
export const ADD_RECIPE_CATEGORIES_SUCCESS = 'ADD_RECIPE_CATEGORIES_SUCCESS';
export const ADD_RECIPE_CATEGORIES_FAIL = 'ADD_RECIPE_CATEGORIES_FAIL';
export const EDIT_RECIPE_CATEGORIES_START = 'EDIT_RECIPE_CATEGORIES_START';
export const EDIT_RECIPE_CATEGORIES_SUCCESS = 'EDIT_RECIPE_CATEGORIES_SUCCESS';
export const EDIT_RECIPE_CATEGORIES_FAIL = 'EDIT_RECIPE_CATEGORIES_FAIL';
export const DELETE_RECIPE_CATEGORIES_START = 'DELETE_RECIPE_CATEGORIES_START';
export const DELETE_RECIPE_CATEGORIES_SUCCESS = 'DELETE_RECIPE_CATEGORIES_SUCCESS';
export const DELETE_RECIPE_CATEGORIES_FAIL = 'DELETE_RECIPE_CATEGORIES_FAIL';

export const FETCH_SHOPPING_LISTS_START = 'FETCH_SHOPPING_LISTS_START';
export const FETCH_SHOPPING_LISTS_SUCCESS = 'FETCH_SHOPPING_LISTS_SUCCESS';
export const FETCH_SHOPPING_LISTS_FAIL = 'FETCH_SHOPPING_LISTS_FAIL';

export const SET_AUTH_REDIRECT_PATH = 'SET_AUTH_REDIRECT_PATH';